apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mycustomoperators.mycustomoperator.example.com
spec:
  group: mycustomoperator.example.com
  names:
    kind: MyCustomOperator
    listKind: MyCustomOperatorList
    plural: mycustomoperators
    singular: mycustomoperator
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
